
services:
  payments-db:
    image: docker.io/library/postgres:18
    container_name: payments-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - payments-network

volumes:
  payments_db_data:
    name: payments_db_data

networks:
  payments-network:
    driver: bridge
